### ISSUE TITLE
January 2018 Checklist

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#471]
**January Checklist**

- [x] Download file system from S3
- [x] Test restore file system from S3
- [x] Download DB's from S3 
- [x] Test restore DB's from S3 
- [x] Upload latest, tested file system to Dropbox
- [x] Upload latest, tested DB's to Dropbox
- [x] check shopping cart plugins
- [x] check OpenCart releases -
**I'm going to start on this process this month. I'll start another issue ticket for it.**
 **See Ticket #475** 

Nothing else has changed since last month:
Opencart 3.0.2 is out, and still seems to be pretty early in it's release and bug sorting. The sheer number of plugins and extensions we use for our shop will greatly increase the complexity of this upgrade since it spans so much time, and none of the extensions are guaranteed to work with newer versions. However the crucial extensions should all be compatible in the very near future.

- [x] check Amember releases
Nothing changed since last moth.  We are running 5.2.5, and 5.4.0 is available. It doesn't contain anything we need, but we can upgrade for free anytime from now until 05/01/18. I'll upgrade all 3 when we do it.
- [x] check for new WP releases
We are running WordPress 4.8.1, and the new release 4.9.1 is now available. I don't think we have to do this upgrade, it doesn't offer anything we need. But if you would prefer, I am more than happy to do it.

**Comment by dustinschaerer** [comment]
@david-huddlestonSince I just performed many of these actions later on in the month of Dec 2017, do you mind if I wait till next Monday to  start on this list?    I've got two projects running over I need to finish up ASAP.

**Comment by dustinschaerer** [comment]
@david-huddleston I'll be working through these items this week as I get time.

**Comment by dustinschaerer** [comment]
@david-huddleston Everything is completed here, and notes are above .  The Opencart upgrade ticket is this issue: #475
