### ISSUE TITLE
March 2018 Checklist

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#476]
**March Checklist**

- [x]  Download file system from S3
- [x]  Test restore file system from S3
- [x]  Download DB's from S3
- [x]  Test restore DB's from S3
- [x]  Upload latest, tested file system to Dropbox
- [x]  Upload latest, tested DB's to Dropbox
- [x]  check shopping cart plugins

- [x]  check Amember releases

- [x]  check for new WP releases
  We are running WordPress 4.8.1, and the newest release is 4.9.3. I don't think we have to do this upgrade, it doesn't offer anything we need. But if you would prefer, I am more than happy to do it.  I'd prefer to wait for version 5, it should be out within a month or two.
