### ISSUE TITLE
November 2018 Checklist

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#486]
- [x]  Download file system from S3

- [x] Test restore file system from S3

- [x] Download DB's from S3

- [x] Test restore DB's from S3

- [x]   Upload latest, tested file system to Dropbox

- [x]   Upload latest, tested DB's to Dropbox

- [x]   check shopping cart plugins

- [x]   check Amember releases - Last Release is 5.5.x. It adds more payment options and newsletter stuff we don't use.  Our upgrade license has passed, so whenever we do want to update, we'll just need to pay upgrade fee again. 

- [x]   check for new WP releases - WordPress 5.0 beta 3 is out, so once WP 5 stable is out, we can upgrade if you'd like. It should be out within a month.

**Comment by dustinschaerer** [comment]
@david-huddleston The checklist is done for November.
