### ISSUE TITLE
November 2018 To-Do List

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#487]
**LINKS to Point**

- [x] 1. Point the link  https://www.soccerhelp.com/practice_games/Dribble.shtml  to  https://www.soccerhelp.com/soccer_drills/Dribble.shtml

 - [x] 2. Point the link  https://www.soccerhelp.com/Soccer_Video_Clips.shtml to https://www.soccerhelp.com/Soccer-Videos-Premium.shtml   

**Change Destination of this Link**
- [x] A. On SH Home page in the alphabetical list , change the destination of the link “Soccer Corner Kicks”  to go to https://www.soccerhelp.com/terms/soccer-corner-kick.shtml
 
**Dustin, Bootstrap and make responsive the following pages** 

- [x] 1. https://www.soccerhelp.com/Patch_Handout.shtml
- [x] 2. https://www.soccerhelp.com/U4-U6-soccer-coaching-leagues-guidelines.shtml
- [x] 3.  https://www.soccerhelp.com/coachdoug-promo/Doug-Testimonials.shtml
- [x] 4.  https://www.soccerhelp.com/Soccer-Drills-For-Beginners.shtml
- [x] 5. https://www.soccerhelp.com/Why_Practice_Games_Are_Better_Than_Soccer_Drills.shtml
- [x] 6.  https://www.soccerhelp.com/soccer-training-drills.shtml
- [x] 7. https://www.soccerhelp.com/drills-for-soccer.shtml
- [x] 8.  https://www.soccerhelp.com/basketball-drills.shtml
- [x] 9.  https://www.soccerhelp.com/terms/soccer-corner-kick.shtml
- [x] 10. https://www.soccerhelp.com/soccer-articles/090413-soccer-goal-kick.shtml
- [x] 11. https://www.soccerhelp.com/terms/soccer-free-kick.shtml
- [x] 12. https://www.soccerhelp.com/Throw-ins_Navigation_Page.shtml
- [x] 13. https://www.soccerhelp.com/terms/soccer-throw-in.shtml
- [x] 14. https://www.soccerhelp.com/Throw.shtml
- [x] 15. https://www.soccerhelp.com/terms/soccer-offside-rule-simplified.shtml
- [x] 16. https://www.soccerhelp.com/soccer-videos/teach-soccer-throw-in.shtml
- [x] 17. https://www.soccerhelp.com/free-soccer-drills.shtml
- [x] 18. https://www.soccerhelp.com/Indoor_Soccer_Drills.shtml
- [x] 19. https://www.soccerhelp.com/Kick-Offs_Navigation_Page.shtml
- [x] 20. https://www.soccerhelp.com/soccer-articles/090416-soccer-corner-kick.shtml
- [x] 21. https://www.soccerhelp.com/Soccer_Moves.shtml
- [x] 22. https://www.soccerhelp.com/newsletter_archive/Soccer_Drills_8_17_2009.shtml
- [x] 23. https://www.soccerhelp.com/Soccer_Dribbling.shtml
- [x] 24.  https://www.soccerhelp.com/basketball-drill-defense-with-feet.shtml
- [x] 25. https://www.soccerhelp.com/basketball-drills-dribble-tag-game.shtml

 **Other Websites to Bootstrap and Make Responsive** 

- [x] 1. SoccerFormation.com ( the text is too small)
- [x] 2. soccerpassingdrills.net
- [x] 3. u6soccer.com (the text is too small)
- [x] 4. soccerpositiondiagram.com
- [x] 5. soccertactic.com
- [x] 6. soccertechnique.com
- [x] 7. Soccerballpatches.org
- [x] 8. SoccerDrills1.com
- [x] 9. Soccerdrillsandgames.com

**Run Broken Link Checker**
- [x] Run and fix links

**Links Pages That Need to Be Cleaned**
- [x] dear_visitor_links.shtml
- [x] graphic_links.shtml
- [x] Keyword_Links.shtml
- [x] Links.shtml
- [x] Links_Two.shtml
- [x] Religious-Christian-Patches-Links.shtml
- [x] School-Rewards-Patch-Links1.shtml
- [x] School-Rewards-Patch-Links2.shtml   -- clean from File System
- [x] soccer-club-league-links.shtml
- [x] Soccer-Drills-Rules-Positions-Links1.shtml
- [x] Soccer-Drills-Rules-Positions-Links2.shtml
- [x] Soccer-Drills-Rules-Positions-Links3.shtml
- [x] Soccer_Attorney_Patch_Links.shtml
- [x] soccer_coaching_tips_drill_links.shtml
- [x] Soccer_Lawyers_Patches_Directory_Links.shtml
- [x] Star-Soccer-Patch-Patches-Links1.shtml
- [x] Star-Soccer-Patch-Patches-Links2.shtml
- [x] Star-Soccer-Patch-Patches-Links3.shtml
- [x] Star-Soccer-Patch-Patches-Links4.shtml

**Check Google Search Console**
- [x] Check for errors, improvements, warnings, etc.

**Comment by dustinschaerer** [comment]
@david-huddleston I turned that list into a GitHub issue so we can track the progress.  I've already cleaned up a bunch of old links.  The broken link checker revealed a bunch of outdated pages I've removed, and showed we need to clean up a bunch more.  Mostly those are those links pages on our site.

**Comment by david-huddleston** [comment]
Great.

**Comment by david-huddleston** [comment]
Shellie and Mandy,

 

The formulas should work in this one - if they don't, let me know.

 

Delete the other form you were using and save this one. I've attached 3
copies.

 

Copy the file and save this email so you can get more copies of the form if
you need them.

 

Create a Folder in My Documents titled >  Inventory Forms

 

Make several copies of this blank form.

 

Each time you use it, make a copy of the form and do 2 things >>

 

1. Put the inventory date on the form

 

2. Re-name the file name so it is the date of the inventory, and delete the
word "Form" - that way you can easily see what is the Blank Form and what is
a filled out Inventory Form.

 

For example - the file name for today will be >> Inventory Mandy & David,
5-31-19

 

The File name on Tuesday June 4 would be >>

 

Inventory Mandy & David, 6-4-19

 

etc.

 

That way we can easily find the Form and the actual Inventories

 

David
