### ISSUE TITLE
December 2018 Checklist

### ISSUE THREAD

**Issue by dustinschaerer** [soccerhelp/soccerhelp#488]
- [x] Download file system from S3

- [x] Test restore file system from S3

- [x] Download server system files from S3

- [x]   Test restore server system files from S3

- [x]   Download DB's from S3

- [x]   Test restore DB's from S3

- [x]   Upload latest, tested file system to Dropbox

- [x]   Upload latest, tested server system filess to Dropbox

- [x]   Upload latest, tested DBs to Dropbox

- [x]   check shopping cart plugins

- [x]   check Amember releases - Last Release is 5.5.5.
The latest releases add options and features we don't need . Our upgrade license has passed, so whenever we do want to update, we'll just need to pay upgrade fee again. We are currently on 5.2.5.
I don't see any reason to upgrade now.

- [x] check for new WP releases - WordPress 5.0 is out, so we can upgrade if you'd like. However, we only use this WP installation to display Coach Doug's site, so it might be smart of us to just get rid of WordPress altogether, so we don't have to maintain it.  There are existing tools I could use to write out all the pages as html files. Then I'd just need to update the internal links or build a new htaccess rule to handle that for us.

**Comment by dustinschaerer** [comment]
- [x]  Bootstrap and  make responsive  https://www.soccerhelp.com/terms/soccer-defend-deep.shtml . the font is too small on mobile. The font on mobile should be like it is on https://www.soccerhelp.com/soccer-drills.shtml or on https://www.soccerhelp.com/terms/soccer-support.shtml

- [x]  check https://www.soccerhelp.com/soccer-articles/120824-Select-Soccer-Formation.shtml on mobile - the font is too small on mobile. The font on mobile should be like it is on https://www.soccerhelp.com/soccer-drills.shtml or on https://www.soccerhelp.com/terms/soccer-support.shtml

- [x]  Have the link First Defender/Second Defender   go to https://www.soccerhelp.com/terms/soccer-support.shtml

- [x] Bootstrap and make responsive https://www.soccerhelp.com/terms/soccer-first-attacker.shtml and have the font on mobile look like https://www.soccerhelp.com/soccer-drills.shtml or on https://www.soccerhelp.com/terms/soccer-support.shtml

- [x] https://www.soccerhelp.com/terms/soccer-push-up.shtml is too narrow on my phone. On mobile, have it look like https://www.soccerhelp.com/soccer-drills.shtml or on https://www.soccerhelp.com/terms/soccer-support.shtml

- [x] Make https://www.soccerhelp.com/Coach_Soccer_Offense_Push_Up.shtml bootstrap and responsive. Have the font on mobile look like https://www.soccerhelp.com/soccer-drills.shtml or on https://www.soccerhelp.com/terms/soccer-support.shtml
